version: "3.8"

services:
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src:delegated
      - ./public:/app/public:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true

  react-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
